trigger:
- main

pool:
  name: Default   # 👈 self-hosted agent

variables:
  appName: 'darsasapp'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

# Windows-compatible zip
- powershell: Compress-Archive -Path * -DestinationPath app.zip
  displayName: 'Archive project'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'node'
    appName: 'darsasapp'
    package: app.zip